### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by arghadipmanna101** [trishit78/Pomodoro-Extension#13]
### Describe your issue

- Will add gif
- Will stylize the readme
- Will add how to contribute

### Steps to reproduce

1. Search the gif link in website.
2. Add in the README using image tag.
3. Add all contribution stapes serially.
4. Will do some changes that is look like good and stylize.

### Would you like to work on this issue?

None

**Comment by arghadipmanna101** [comment]
please assign me under Apertre

**Comment by trishit78** [comment]
I think the README has a good demo section having a gif of the project, you can add a CONTRIBUTING.md  
@arghadipmanna101

**Comment by arghadipmanna101** [comment]
ok'

**Comment by trishit78** [comment]
completed
